# Generated by Django 6.0.1 on 2026-03-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_category_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackentry',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
